spec.md
This PR corrects two small issues I spotted while browsing this doc. See commit message bodies for more-detailed descriptions of the two changes.
=> Correct issues with module description

include/firrtl.xml, spec.md
Not really sure how to add `AsyncReset` into the https://github.com/chipsalliance/firrtl-spec/blob/main/spec.md#firrtl-language-definition section... should it go into `type_ground`?
=> Adding async reset info

revision-history.yaml, spec.md
Specify that combinational loops are not allowed in FIRRTL
=> [Minor] Define Combinational loops

CONTRIBUTING.md
Mostly wanted to record our preference for wrapping to 80 chars, but added a few other suggestions too.
=> [nfc] Add a short list of "style" preferences to CONTRIBUTING.

revision-history.yaml, spec.md
Reuse the machinery of modules for intrinsics.  This allows a pretty wide range of intrinisics to be defined.
=> [minor] Intrinsics via modules

spec.md
Leave single-chars as-is for now.
=> [nfc] Fix more unstyled FIRRTL snippets

revision-history.yaml, spec.md
Touchup some probe-related examples in spec.
=> [patch] Fixup probe-related examples.

abi.md, revision-history.yaml, spec.md
This PR is to open the discussion about a new kind of type: property types. It describes property types, without adding any concrete new types. My hope is to use this PR to at least get commitment that these types will exist, and add concrete property types and related constructs to the spec in future PRs.
=> Add initial description of property types.

include/firrtl.xml, revision-history.yaml, spec.md
Defines the propassign statement and legal property assignments.
=> Add property assignment.

revision-history.yaml, spec.md
This adds the integer multiply operation to the Integer Arithmetic section and list of primitive operations in the grammar.
=> [minor] Add Property primitive operation for integer multiplication.

.github/workflows/continuous-integration-ci.yml, abi.md, include/circt.json, revision-history.yaml, scripts/extract-firrtl-code.lua, spec.md
Fix all broken code examples. Add code example checking to CI.
=> [patch] Fix broken code examples, add CI

spec.md
Responding to #196.
Looking closer at the table, I'm not sure that the data is represented in an entirely consistent way. But I can't imagine this will cause confusion.
=> Add eq, neq to operations table.

revision-history.yaml, spec.md
LHS and RHS are swapped in the flow "intuition" section.  Further, the flow section no longer describes how flow propagates.
=> Fix some bugs introduced in #136

revision-history.yaml, spec.md
Also fix trailing comma between "|"s.
=> [patch] restore id/info on printf, add to verif commands.

include/firrtl.xml, revision-history.yaml, spec.md
This defines the List property type, and primitive operations to construct a List and concatenate Lists.
=> [minor] Add Property type and operations for List.

CONTRIBUTING.md
=> [nfc] Update CONTRIBUTING.md

.github/workflows/cd-circt.yml, .github/workflows/continuous-integration-ci.yml, .github/workflows/update-contributors.yml
Bump GitHub actions and runners to latest available versions.
=> [nfc] Bump Runners and Actions

revision-history.yaml, spec.md
- Enhance fprintf to support format strings for file paths
- Add fflush statement for explicit buffer flushing
=> [minor] Add dynamic file to fprintf and introduce fflush

revision-history.yaml, spec.md
This commit changes a cat to accept variadic inputs including zero inputs (= UInt<0>(0)).
=> [minor] Change cat to accept variadic inputs

.github/workflows/continuous-integration-ci.yml, CONTRIBUTING.md, README.md, spec.md
Bump Pandoc to the latest version, 3.7.0.2, and apply formatting fixes.
=> [nfc] Bump Pandoc to 3.7.0.2
