- .github/workflows/pandoc.yml
Add a GitHub Actions CI pipeline that builds the PDF version of the spec
from the source Markdown.  (This uses a combination of a Pandoc docker
image followed by a LaTeX docker image to temporarily work around a bug
in the Pandoc docker image [1].)  The results of the build are uploaded
as a GitHub Actions artifact with an expiration of one day.  This is
done to enable users to check the output of what they built (or to debug
problems where the local installation of pandoc + LaTeX may differ from
what runs in CI).  Finally, if the commit is tagged then a new release
is created where the built PDF spec is added as an additional file.
Fixes #2.
[1]: https://github.com/pandoc/dockerfiles/issues/167
> Add GitHub Actions CI to Build/Release Spec

- scripts/get-contributors.sh
- spec.md
Change the authorship of the specification from the original tech report
authors to "The FIRRTL Specification Contributors".  Change the
Acknowledgments section to remove the original tech report "thank yous"
and explicitly mention all papers that contributed to the spec (the
original tech report with authors called out by name, the ICCAD "FIRRTL
Ground" paper, and Adam's Thesis).  Finally, add a list of all
people (GitHub handles w/ hyperlinks) that have contributed to the
FIRRTL specification (as evidenced by GitHub's contributor tracking
which is backed by the original git log).
Fixes #1.
The specification now looks like: [spec.pdf](https://github.com/chipsalliance/firrtl-spec/files/8227498/spec.pdf)
> Rework authorship as The FIRRTL Spec. Contributors

- spec.md
This changes the spec to allow implicit truncation and extension for
register reset values, which matches both the original FIRRTL compiler
and the CIRCT compiler's behaviour.
> Register reset values must be `equivalent`, not the same

- spec.md
> Fix typo: an a manner -> in a manner

- spec.md
~Since 0.4.0 we added a lot of information missing from the spec so seems we should bump and re-release the doc.~ The 0.4.0 version bump post-dated adding the missing stuff. So changing this PR to  say something about the versioning scheme of this document and when to bump each version.
> Add a versions Table, define versioning scheme, and bump version to 1.0.0

- spec.md
Make the version include a unix-style  magic string for file identification.
> Add a version preamble to fir files.  

- Makefile
- include/spec-template.tex
- spec.md
Change the way that the version is computed to be derived from the
latest git tag that looks like `v*.*.*`.  This _should_ compose
correctly with the GitHub Action to build/publish the spec once a new
tag is created.  This also has the benefit of never having to manually
update the spec version.  Instead, only a new tag has to be created.
Closes #33 (as this is an alternative that avoids ever having to bump the version again).
If you build off of a spec version that is some commits after the latest tag you get something like the following:
A clean tag (which is what the CI will do on a release) will give you something like:
For a git history of:
```
* d73da20 (HEAD -> dev/seldridge/use-git-tag-for-version, tag: v1.42.1337, …
```
> Use git-tag to compute spec version

- spec.md
'en → pred' is vacuously true when 'en' is false,
we want model checker to make pred true when en is true
(not find a way to make 'en' false, for example).
> cover: goal is 'en and pred', not 'en → pred'

- spec.md
Make explicit that FIRRTL is a 2-state language and only defined on 2-state values.  This allows a compiler to ignore the x-prop and z  behavior in verilog (and similarly in VHDL) when transforming circuits.
This matches the spec to the current behavior of compilers, which have so far presumed this without it being specified.
> Specify FIRRTL is 2-state, and limit observable behavior to that

- spec.md
This clarifies that all zero-width integers are zero extended which matches the current behavior of the `firrtl` compile.
Furthermore it allows UInt<0>(0) and SInt<0>(0) zero-width integer literal values.
> clarify semantics aroud zero bit width integers

- revision-history.yaml
We forgot to record https://github.com/chipsalliance/firrtl-spec/pull/40 in the revision-history.
> Update revision-history with zero-width changes

- spec.md
The text on registers was pretty sparse and didn't hint at their behavior.  Update this and mention the type-dependent reset behavior here.
> Expand register text with at least cursory explanation

- revision-history.yaml
- spec.md
Add clarifications to the spec that FIRRTL has both ground types and aggregate types.  The latter term "aggregate types" is used, but not defined.  Also, restructure the spec to include an explicit "aggregate types" section that is at the same level as "ground types"  Move vector and bundle types under this new "aggregate types" section.
> [patch] Add Explicit Info About Aggregate Types

- revision-history.yaml
- spec.md
Indeterminate values are underspecified.  This expands the constructs with explict indeterminate value to include register initialization.  This further describes the implementation constraints on how indeterminate values behave.  This is intended to make the current behavior, which changes visible behavior of circuits with indeterminate values, consistent with the spec. 
Namely, current implementations will replace a register with a constant if the constant is written at some point (say reset), if there are no other writes.  This changes the observable state of the register between power-on and first write.
> [patch] Specify the behavior of "indeterminate values"

- revision-history.yaml
- spec.md
Remove Fixed Point and any references to it from the FIRRTL
specification.  This (and intervals) was not a FIRRTL feature that
achieved significant traction nor was it ever load-bearing in the same
way that the rest of the specification has been for many years.
This is not in any way intended to be the end of Fixed Point
representations in FIRRTL (or Chisel)!  There are planned future
improvements to provide Fixed Point libraries either directly in Chisel
or via user-defined FIRRTL types once we sort through what that should
look like.
> [major] Remove Fixed Point Types

- revision-history.yaml
- spec.md
Add inline JSON annotations for FIRRTL Circuits to enable the annotation file to be provided in the same file as the circuit.  This is a format that has been used for a while by CIRCT and makes it easier to package the annotation file along with the FIRRTL file.
> [minor] Add inline circuit annotations

- revision-history.yaml
- spec.md
Remove the validIf expression from the spec.  This expression is an artifact of the Scala-based FIRRTL Compiler's internal representation and how it lowers conditional expressions.  It is not necessary that this is part of the public-facing FIRRTL spec.
> [major] Remove validIf

- revision-history.yaml
- spec.md
Change the FIRRTL spec to state that connects are truncating (like partial connects).  This has always been the way that connects work in the Scala-based FIRRTL Compiler and the spec was always incorrect here.
My plan here is to remove partial connect and eventually add a "strict connect" operator that does neither truncation nor sign extension.  (This has been used for a while internal to the MLIR-based FIRRTL Compiler to great benefit.)
> [major] Change connect to be truncating

- revision-history.yaml
- spec.md
It looked like we were using "behavior" (10 instances) more than "behaviour" (5 instances), so I went with the more common one.
> [patch] Fix minor spelling and grammar issues

- revision-history.yaml
- spec.md
Remove the partial connect operation ("<-").  This commit should be merged once it is no longer possible for Chisel to emit partial connects.
> [major] Remove Partial Connect (<-)

- revision-history.yaml
- spec.md
Remove all discussion of FIRRTL forms and lowering, i.e., high/mid/low FIRRTL.  Add language to indicate that high-level constructs may be preserved or eliminated by a FIRRTL compiler implementation.
> [major] Remove Discussion of FIRRTL Forms

- revision-history.yaml
- spec.md
Strictly speaking, sub-index and sub-access have different out-of-bounds behaviors.  Since a sub-access returnes an indeterminate value and sub-index has a compile-time error, one cannot convert sub-access with constant index to a sub-index if the index is out-of-bounds.  This explicitly allows that conversion.
> [Clarification] Allow sub-access to convert to sub-index.

- revision-history.yaml
- spec.md
Tweak the existing field to match its use in practice (SFC), and planned to soon behave similarly in MFC: https://github.com/llvm/circt/pull/4502 .
See #53 for discussion of this field, for now let's keep existing code working and update spec to reflect current behavior (and provide users a means to attach string information to the output that's not limited like `optional_name`).
> [patch] Clarify cover string argument as comment not message.

- spec.md
At least on my local pandoc/etc setup, without the newline it renders like:
After:
> [nfc] Fix markdown list, separate with blank line before.

- revision-history.yaml
- spec.md
Condtionally valid (`validif`) was removed in 9890f17f2d .
> [patch] Drop language about width of conditionally valid.

- spec.md
My assumption is that the examples provided are missing the `input v` port that was defined in the earlier example. Otherwise, `v` is undefined in the circuit.
> [patch] Fix missing ports in indeterminate example

- revision-history.yaml
- spec.md
Add a constant type modifier for compile-time evaluation (under whole-world assumptions).  Constant types in external ports implies that uses of constant types are not guaranteed to be know at compile time (this is not a mechanism to guarantee constant propagation).
Asynchronous resets are updated to take constant reset values.  This moves ad-hoc checks which exist in implementations now to type checks.  This is not sufficient for some tools, but is a strict improvement on the current implementations.
The change of asyncreset value is what makes this a major change.
> [Major] Explicit compile time constant expressions.

- spec.md
Also fix typos re:`{.firrtl}`.
> [nfc] Fix unstyled FIRRTL code in const-related text.

- include/firrtl.xml
- revision-history.yaml
- spec.md
Apparently we can bounce to other syntax definitions, use that to make inline annotations render nicely.
Also fix unstyled inline anno while visiting.
Modeled this after https://github.com/KDE/syntax-highlighting/blob/2880570764a754bdf2ed402d6fd24024a35bf5bc/data/syntax/markdown.xml#L421 , seems to work for our use case.
> [patch] Render inline annotations as JSON, fix typo in example

- include/firrtl.xml
- revision-history.yaml
Fix rendering const types in PDF.
> [patch] Add syntax support for type modifiers (e.g., const).

- revision-history.yaml
- spec.md
* Missing comma between reset value and closing paren.
* Wrong punctuation ("{" vs "(" around reset)
* Drop outer parentheses around "with :" portion.
* Break string literal into tokens. (Generally useful, but specifically support the whitespace variations in document such as "with:" vs "with :")
> [patch] Fix grammar for registers.

- include/firrtl.xml
- revision-history.yaml
- spec.md
Introduce "reference types" for indirect access to FIRRTL constructs.
Add operations for generating probe references and using them to remotely access data (via XMR's).
Enable expressing XMR's, particularly testing/verification scenarios, with minimal impact on the generated design other than requiring visibility of the probed elements.  The goal is both testbench and design can be written in FIRRTL and have type-safe XMR's robust to hierarchy changes during compilation.
Second goal is to serve as pathway for producing resolved paths to signals for use in "raw" SV (e.g., testbench).  Specifically, supporting the ability to use SV "force" on a probe (`RWProbe<T>`) is a requirement.  These are typed differently as they cause much more conservative handling by the compiler.
To ensure a valid …
> [major] Add reference types.

- revision-history.yaml
- spec.md
Add language that explicitly defines literal types:
1. Integer literals
2. String literals
3. Raw String literals
4. String-encoded integer literals
This only clarifies existing behavior which was left ambiguous or documented in different locations in the spec.
Define that string-encoded integer literals can be used any place that an integer literal can except where specified otherwise.  This is used to differentiate where an external module parameter that looks like a string-encoded integer literal is still a string.  This is also used to preserve the existing SFC behavior where a string-encoded integer literal is not allowed to be used for memory integers.
Notably, this is enshrining the fact that you can do things today like:
```
circuit Foo:
module Foo:
input clock: Clock
input a: …
```
> [patch] Clarify Int/String Types, clarify SE-Ints

- revision-history.yaml
- spec.md
* Force expects expression as value, not integer literal.
* two-argument force is 'force_initial', fix in example.
* Fix typo/use of wrong variable in when condition.
> [patch] Fixup force/release examples.

- revision-history.yaml
- spec.md
This isn't really generally useful but might as well allow it as it's useful for examples (such as those in spec already!).
Note you still can't `read(probe(x).y)` but not worth allowing when you might as well `read(probe(x.y))`.
> [patch] Tweak read grammar to allow read(probe(x)) as in examples.

- revision-history.yaml
- spec.md
- `asAsyncReset` was missing from `primop_1expr_keyword` (should have been in #25)
- `force_release` was incorrectly changed to a keyword in #95
> [patch] Simple syntax tree fixes

- spec.md
I am currently writing a FIRRTL lexer for [Pygments](https://pygments.org/) and stumbled upon some minor issues in the formal specification that I fixed. Furthermore I found some curiosities in the specs as well as a mismatch between what Chisel 3.5.5. produces and what is described in the spec. 
* Removal of unnecessary parentheses and a spurious colon
* Allowing to create decimal integer expressions (the compilers, of course, always allowed for that)
* Enforcing an `at least once` constraint in many places. The grammar uses `{ rule }` quite often when `rule , { rule }` should have been used. I do not know what formalism exactly is used in the "FIRRTL Language Definition", but as it looks XBNF enough for me, I opted to use the `{ rule }+` notation to indicate the "at least once" …
> Minor grammar changes

- spec.md
Change the spec to require that Bundle fields are legal identifiers. Currently, the SFC has historically accepted anything, including numbers for fields.  This stems from the MixedVec Chisel utility which emits numeric fields.  Change this to make lexing FIRRTL easier.  Currently, there is extreme ambiguity for something like "0.0".  This could be either a subfield or a floating point number.  By restricting subfields to require legal identifiers, this becomes illegal and the ambiguity is resolved.
Note: the EBNF description is already correct here.
> [major] Require Bundle fields are legal IDs

- include/firrtl.xml
- revision-history.yaml
- spec.md
Add alternative syntax for specifying a register with a reset.  This is done to simplify parsing, readability, and writability.  This also brings the register more in line with other FIRRTL operations.
The new syntax looks like:
regreset a: UInt<8>, clk, rst, init
The old syntax that this is an alternative to is:
reg a: UInt<8>, clk with: (reset => (rst, init))
This syntax is intended to be introduced in the v2.3.0 minor release and made mandatory in the v3.0.0 release.
---
An alternative to this syntax would be to use:
reg a: UInt<8>, clk, rst, init
I didn't do this as it seems easier to just use a new keyword as opposed to making `reg` variadic.
> [minor] Add "regreset" alternative syntax

- include/firrtl.xml
- revision-history.yaml
- spec.md
Add literal identifiers which are identifiers that are escaped with
backticks.  This is used to encode an identifier which (extremely
narrowly) is an identifier but starts with a leading number.  This enables
extremely simple lexing and avoids any confusion with other possible
number types, e.g., floats or versions.
Add language that describes how this works for subfields.  E.g., to
subfield into an aggregate "foo" with field "`0`" you would do "foo.`0`".
---
Implements the @darthscsi suggestion from https://github.com/chipsalliance/firrtl-spec/pull/101#issuecomment-1529312052 with suggestions from @jackkoenig to use backticks.
The main use of this is to allow for numeric identifiers to not require context-sensitive lexing. E.g., `foo.0.0.bar` requires context passed from the parser to …
> [major] Add literal identifiers, e.g., `0`

- include/firrtl.xml
- revision-history.yaml
- spec.md
Add product types to firrtl.  These are called enums after rust and swift.  Other languages might call them discriminated unions.  The type carries a discriminator which is a set of identifiers, each a tag corresponding to one variant.  The type also carries a union, with each variant of the union corresponding to a specific tag.  A value of enum type will have one tag and the data associated with that tag.  Match statements provide a way to decompose an enum.  Enum construction is provided in the same manner as ground types.
An enum with empty fields (just tags) is expected to map to a Verilog enum.  An enum with fields maps to a verilog tagged union in spirit, but due to almost no tools support synthesis of packed tagged unions (or even just packed tagged unions as a recognized type), …
> [minor] add enumeration types and match statements

- revision-history.yaml
- spec.md
Restrict the usage of string-encoded integer literals to only being
allowable used in the construction of hardware integer literals.
Change string-encoded integer literals to radix-specified integer literals.
E.g., make the following change:
"b10101" to 0b01010
Remove string-encoded integer literals.  Continue to disallow the usage of
radix-specified integer literals in any location other than hardware integer
literal construction.
> [major] Only allow se-ints in hardware literals, change se-ints to radix-encoded ints

- include/firrtl.xml
- revision-history.yaml
- spec.md
Remove the old connect ("<="), invalidation ("is invalid"), and register
with reset ("with: (reset => (resetSignal, resetValue))") syntaxes in
favor of syntax which does not require lookahead when parsing (connect and
invalidate) and simpler syntax (register with reset).  The new syntaxes,
which wer added as "alternative syntaxes" previously, are "connect",
"invalidate", and "regreset".
This is a major breaking change that becomes active in the 3.0.0 release.
> [major] Switch to 3.0.0 Syntaxes

- revision-history.yaml
- spec.md
truncation was intended to be limited to partial connect, not connect.  This was changed 5 months ago.
> Remove unintended truncation behavior

- revision-history.yaml
- spec.md
Don't require inferring selector to 1-bit:
* Support inferring to zero-bit (will be padded)
* Don't put constraints on operands ("back-propagation").
* Align with behavior in similar constructs: when, subaccess.
As-is selector can be entirely unconstrained otherwise, but will inferred to one-bit when used in a mux.
This masks design bugs and has no known utility.
Further, by requiring inference to 1-bit this can cause hardware that otherwise would be zero-width (and often elided) to become 1-bit and kept around.
Instead treat the selector like any other operand, but still reject if selector is inferred to be larger than 1 bit.
See https://github.com/llvm/circt/issues/5444 for further discussion and examples demonstrating the issue on current and historical implementations.
> [patch] Tweak mux selector width-inference behavior.

- revision-history.yaml
- spec.md
While current implementations ignore commas when parsing, this is not what the grammar says and more to the point as-is the use of commas makes the proper printf syntax invalid.  Fix.
> [patch] Fixup printf grammar to reflect need for commas between exprs.

- include/firrtl.xml
- revision-history.yaml
- spec.md
This adds the first concrete property type: Integer. Integer
properties are arbitrary bit width integer values. This also indicates
where concrete property types are legal, and updates the grammar. For
now, the only legal location is in ports.
> Add Integer property type.

- revision-history.yaml
- spec.md
This defines literal property type expressions in general, and Integer property type literals specifically. Examples are added to show example Integer literals, as well as using literals in propassign statements.
> Add Integer property literals.

- abi.md
- include/firrtl.xml
- revision-history.yaml
- spec.md
Alternative to adding remote instantiation.  This introduces a "group" concept which is a way of putting a bunch of statements in a box which are destined to live in a bind.
This introduces a "defgroup" which enables a circuit or external module (which are two things which should be fungible) to declare that it has groups.  Because SystemVerilog bind disallows bind-under-bind, we need some way of guaranteeing that a specific extmodule/circuit is not later bound.
There is a middle-ground solution which would add remote instantiation indicating a group (h/t @mwachs5) and `defgroup`.  This would likely simplify some of the complexity by adding `group`.  However, the same rules of a `group` should likely apply to a remote instance, e.g., a remote instance/group cannot drive anything in the …
> [minor] Add groups

- include/firrtl.xml
Allow nesting "outertype", and treat literals
more like normal functions.
Changes `UInt<1>(0)` but also fixes various
places where the type context persisted
after ending, such as when used inside
expressions like `when eq(n, UInt(0)) :`.
Fixes rendering of `RWProbe<T, A.B>`.
Cleanup but also preparation for adding new
types and literal expressions where this is needed.
> [nfc] Tweak syntax highlighting rules.

- revision-history.yaml
- spec.md
This PR fixes the location of the "Type Alias" alias, which was inserted in the middle of the "Reference Types" section. Consequently, some subsections of "Reference Types" are wrongly attached to the "Type Alias" section.
This dates back to b037c7662240450077b0c09e82cd377076412733 and it can be observed in the 3.1.0 version of the specification (see for instance subsection 7.4.0.1, "Width and Reset Inference").
Additionally, this PR enforces the 80 characters maximum width in some places.
> Fix "Type Alias" section location. 

- abi.md
- include/firrtl.xml
- revision-history.yaml
- spec.md
Add a notion of "public" modules to FIRRTL.  A public module is a module that has a defined Verilog ABI.  A user can look at a FIRRTL circuit and expect to see Verilog modules with expected ports and names after compilation.  The notion of a circuit is then expanded to allow for any number of public modules.  The instance graphs of public modules may or may not share common children. In effect, a circuit is now collection of multi-rooted instantiation trees.
Any public module that is instantiated by other modules has certain restrictions on its lowering.  It follows one of the port lowering ABIs and no information from its instantiating context(s) may be used to optimize into it.  (You cannot constant prop into a public module.)  However, it is allowable for modules which instantiate the …
> [major] Add public modules

- spec.md
As far as I can tell, the grammar for FIRRTL was originally created with two design points:
- Make a pretty, whitespace-sensitive language.
- Just make it work.
The current grammar is overgrown and in need of a refactoring. I have made several changes to help illuminate the structure of the FIRRTL language:
- The organization of the production rules has been tightened up a bit
- Several grammar rules have been renamed for uniformity or clarity.
-The `expr` production rule  has been change to an alternate list of non-terminals
-The `statement` production rule  has been change to an alternate list of non-terminals
The `expr` and `statement` production rules now allow you to glance at the grammar and get a reasonable idea of what a language-level AST should look like. For `statement` …
> [patch] Refactor Grammar

- spec.md
@seldridge and I wish to move to a world where we have one sentence per line.
The `spec.md` file had been formatted to fit in an 80-line terminal, applying line wraps to everything. This makes diffing difficult and suggests a rather specific editor setup.
This will likely cause conflicts with existing PRs. Please ping me if there's a PR you're trying to merge, and I will help apply them.
> [nfc] Reformat source to have one sentence per line

- spec.md
As of version 3.2.0, the FIRRTL Spec makes several references to a notion called a "circuit component", including in the introductory chapter.
This latent concept seems to capture the important notion we informally refer to at the Chisel level as "hardware".
I'm adding a section early on to properly define this concept and to raise salience of this important notion of FIRRTL.
The sections these references appear are given with the numbers above each section:
2.1
Chisel designers manipulate circuit components using Scala functions, encode their interfaces in Scala types, and use Scala’s object-orientation features to write their own circuit libraries.
7.2.2
In a connection between circuit components with bundle types, the data carried by the flipped fields flow in the opposite direction as …
> [nfc] Define Circuit Components

- revision-history.yaml
- spec.md
- Move "Primitive Operations" section closer to the bottom.
- Rename a "FIRRTL Language Definition" to "Grammar".
- Rename "Details about Syntax" to "Notes on Syntax".
> [nfc] Reorganize and Rename Appendices

- spec.md
The section Connects is in need of reorganization.
The Connect section has been lifted out of the Statements section (which I'm aiming to remove eventually in a future PR) and renamed to Connections.
The section on Flows has been moved under Connections and placed at the start (since the connection rules are defined in terms of Flow). The rules for Flow have been elaborated. Some motivation has been given. I avoid leaning on the phraseology, "all other expressions" in favor of naming the remaining classes of expressions explicitly.
I might not touch it in this PR, but I would like to keep my eye on the Last Connect Semantics section. It is now the only section which isn't related to the legality of connects, and it has interactions with conditionals. This suggests that it will probably be …
> [patch] Reorganize section on Connections

- CONTRIBUTING.md
- revision-history.yaml
The new policy for line formatting is in `CONTRIBUTING.md`: One sentence per line.
This makes diffs easier to read and the text easier to shuffle around.
This PR also adds in a line I forgot to include in `revision-history.yaml` in #135.
> [nfc] Change line-wrap policy in `CONTRIBUTORS.md` and add missing revisions

- revision-history.yaml
- spec.md
The Statements section in the spec is not so much a listing of all the statements as it is a container for all non-type, non-expression topics in the language.
This PR doesn't change any copy. It only changes the organization of the sections under the Statements heading. 
Reading the commit messages should be sufficient to understand the entirety of what this PR does.
> [patch] Remove Statements section

- include/firrtl.xml
- spec.md
This PR re-orders a few sections under the Types section. The easiest way to review this is commit-by-commit.
Also, add `type` as a keyword for syntax highlighting.
No copy has been changed.
Some high-level points:
- Float property types up, since they are the four tier of the standard taxonomy (along with ground and aggregate and reference types).
- Move passive types up, since that feature is central and very stable.
- The probes section had a bunch of copy that isn't relevant to the type system and has been moved to the section of probes below.
All of this is prepwork for a heavy upcoming rewrite of the types section.
> [patch] Types Section Reorg

- spec.md
Add language to the spec that allows multiple group definitions in the same module to reference the same group declaration.
This is done as it is more straightforward to have Chisel create groups whenever a module's constructor runs as opposed to waiting until the module is "closed" before creating a group.  Modules may have arbitrarily complex levels of inheritance and there's no great reason to force Chisel to have to combine groups itself.  This also forces Chisel users of groups to not treat groups as arbitrary scope escape hatches where anything defined in a group is visible to anything in a later declared group.  This better matches Chisel's scoping rules where it tries to align with Scala scoping rules.
This change does not disallow _merging groups_ in a FIRRTL compiler.  This is …
> [patch] Allow multiple group defs with same decl

- abi.md
- revision-history.yaml
- spec.md
This PR is a moderate rewrite of the entire Types section.
This is best reviewed by building the PDF and reviewing paragraph by paragraph.
Here are some highlights:
- Uninferred types are mentioned in their own section. (Both width and reset inference).
- The section on zero-width integers is abbreviated. (It warrants mention, but doesn't need so much ink spilled)
- Analog type is scooched down.
- Small code formatting of FIRRTL (eg, spaces between braces in bundle types)
- Reword section on flips with bundle types.
- Rename "Reference Types" to "Probe Types"
- Move several examples of FIRRTL programs using probes out of the Probe Types section and into the probes section.
> [patch] Rewrite Types Section

- .github/workflows/pandoc.yml
- spec.md
Format the spec using pandoc.
Add a check that Markdown formatting is correct as part of CI.  Print the
diff as part of the GITHUB_STEP_SUMMARY if it fails.
Avoid installing pandoc when running "make format" in CI.  This allows
formatting checks to run before the lengthy installation of TeX Live.
Example output is here: https://github.com/chipsalliance/firrtl-spec/actions/runs/6792969106
This needs to land _after_ formatting is applied to `main`.
> [nfc] Format Spec, Add Formatting Check to CI

- .github/workflows/pandoc.yml
- Makefile
Switch to `latexmk` and turn on `-Werror`.
Example output with this for an undefined reference:
```
pandoc spec.md --metadata-file spec.yaml --metadata-file=revision-history.yaml --metadata-file=include/common.yaml --pdf-engine=latexmk --pdf-engine-opt=-logfilewarninglist --pdf-engine-opt=-Werror --pdf-engine-opt=-silent --template include/spec-template.tex --syntax-definition include/firrtl.xml --syntax-definition include/ebnf.xml -r markdown+table_captions+inline_code_attributes+gfm_auto_identifiers --filter pandoc-crossref --metadata version:3.2.0-24-ga941e59-dirty -o build/spec.pdf
WARNING: pandoc-crossref was compiled with pandoc 3.1.5 but is being run through 3.1.8. This is not supported. Strange things may (and likely will) happen silently.
Latexmk: ====List of undefined refs and …
```
> [nfc] Make LaTeX Warnings Errors

- include/spec-template.tex
Modify the LaTeX template to make the "quote" environment more like commentaries/asides.  This is modeled after how the RISC-V Specification does commentary with an indented, italicized region with a "\rule" at the top.
With the following diff:
```diff
diff --git a/abi.md b/abi.md
index 2ab8853..a4042c8 100644
--- a/abi.md
+++ b/abi.md
@@ -3,6 +3,26 @@
FIRRTL defines a language/IR for describing synchronous hardware circuits.
This document specifies the mapping of FIRRTL constructs to Verilog in a manner similar to an application binary interface (ABI) which enables predictability of the output of key constructs necessary for the interoperability between circuits described in FIRRTL and between other languages and FIRRTL output.
+> Thanks for reading the document.
+> Thanks for reading …
```
> [nfc] Make block quotations commentary-like

- spec.md
Adds a section defining Circuit Subcomponents.
This notion is latent in the implementations, but is central to FIRRTL's semantics. 
Intuitively, subcomponents are what you "dot into" or "index into". Eg, `c[0].x` is a reference to a subcomponent of a circuit component `c`.
Circuit subcomponents unify the notion of references, both static (sub-index and sub-field) and dynamic (sub-access). They are the entities which are the targets of a connect (... I believe this is a categorical statement). They are also important for reasoning about the initialization coverage of a module definition.
> [patch] Define Circuit Subcomponents

- abi.md
- include/firrtl.xml
- spec.md
Change optional groups to "layers".  This much better captures the underlying concept as well as the possibility of nesting.  Change `declgroup` to `layer`. Change `group` to `layerblock`.
I recognize this is a pretty disruptive change. However, being able to explain this with the correct terms is highly beneficial. I always had difficulty talking about "nested optional groups" while "nested layers" makes more sense. I'm trying to draw analogies to layers in graphic design or existing [software engineering concepts](https://en.wikipedia.org/wiki/Layer_(object-oriented_design)).
This also inverts the focus in a good way. Layers are really about a collection of optional functionality in "layer blocks" that exists across disparate modules. The previous description incorrectly inverted this: …
> [major] Rename groups to layers

- spec.md
> [nfc] Typo in grammar: Should be circuit_component_reg, not conditional_reg

- revision-history.yaml
- spec.md
This PR defines a new term "Storable Type" which captures the class of FIRRTL types which are admissible inside of registers and memories.
Yes.
The definition has a large overlap with the term Passive Type. And that is not a coincidence.
The term Passive Type has been used to designate 'types without flips'. However, with the introduction of Probe Types and also Property types, more nuance is required to handle types. Arguments have been made both for and against the above types being allowed be passive.
In order to help resolve this tension, the new term Storable Type is intended to separate out one particular usage of Passive Types.
Some notable differences between Passive and Storable:
1. Clocks and Resets are Passive but not Storable
1. Analogs are Passive but not Storable.
1. …
> [patch] Define Storable types

- revision-history.yaml
- spec.md
Change the minimum width of the result of "Shift Right" to 0-bit to align the behavior between Chisel and CIRCT.
Context: https://github.com/chipsalliance/chisel/pull/3752#issuecomment-1905086931, https://github.com/chipsalliance/chisel/pull/3752#issuecomment-1906225248 and chipsalliance/chisel#3735.
> [major] Change the minimum width of the result of "Shift Right" for UInt to 0-bit

- revision-history.yaml
- spec.md
This commit allow assert statement's message string to be a format string which is corrently expressed as printf-encoded assertion. CIRCT side PR is https://github.com/llvm/circt/pull/6621 
This also adds missing grammar for verif statements.
> [major] Allow assert message to be a format string

- revision-history.yaml
- spec.md
This adds prose to the Expressions section introducing the concept of
primitive Property operations, adds a new section defining the
primitive Property operations, and adds primitive Property operations
to the grammar.
As a concrete example, integer addition is included.
> [minor] Add Property primitive operations, starting with integer addition.

- .github/workflows/update-contributors.yml
Change the "Update Contributors" action to use the CHISEL_BOT_TOKEN secret.  This enables the PR created to trigger CI.
> [nfc] Use Chisel Bot Token for CI

- include/firrtl.xml
- revision-history.yaml
- spec.md
Define semantics and an ABI for layer-associated probes.  ~This introduces a major change to the existing layer ABI where layers are now enabled with a Verilog text macro (`` `define ``) and not by including a file.  This is done to unify the enabling of all layer collateral which can include modules/logic _and_ new probe ports (which were not supported previously).~
This uses a basic ABI where all layer-colored probes are always emitted. We may want to change this in the future to use an ABI where Verilog macros are conditionally defined. However, it is much simpler to start without this. It is also not clear that such an ABI provides much over just requiring a user to enable a layer for the reference to be valid.
> [major] Layer-associated probe semantics and ABI

- revision-history.yaml
- spec.md
This adds the integer shift right operation to the Integer Arithmetic section and list of primitive operations in the grammar. This is defined as signed arithmetic shift right, as opposed to logical shift right, using similar language to the dshr operation.
> [minor] Add Property primitive operation for integer shift right.

- include/firrtl.xml
- revision-history.yaml
- spec.md
Not used presently, simplify.
Generating appropriate ABI information can be used to arrange for similar effect.
cc https://github.com/llvm/circt/issues/6715 .
> [major] Drop ref statements.

- CONTRIBUTING.md
- Makefile
- scripts/extract-firrtl-code.lua
This demonstrates a flow that can be used to validate that all code
snippets used in the FIRRTL specification correctly parse.  This is
implemented using a simple pandoc filter to extract the bodies of all code
blocks with known languages (FIRRTL and Verilog), write them to the build
directory, and then run them all through an appropriate tool based on file
extension (firtool or verilator).
This may be a little cumbersome as every code example has to be completely
legal.  To alleviate this, this PR includes the ability to add special
delimiters, indicated by lines with the text `snippetbegin`/`snippetend` which
will cause the filter to extract only the lines between the delimiters.
CC: @dtzSiFive
> [nfc] Add ability to test code snippets

- revision-history.yaml
- spec.md
Not used in practice and have restrictions that they must be basically equivalent to a design that doesn't use them at all.
> [major] Drop input probes from spec.

- revision-history.yaml
- spec.md
Clarify main module is implicitly/always public.
Update examples to specify widths (and concrete reset type).
Some of these are invalid regardless (e.g., "input foo : UInt" on main module) but recent CIRCT checks this now while parsing.
> [major] Main module is public.

- .github/workflows/continuous-integration-ci.yml
Bump both pandoc and pandoc-crossref now that the latter has a release compatible with the latest pandoc version.
> [nfc] Bump pandoc/pandoc-crossref

- revision-history.yaml
- spec.md
Remove the syntax note that that commas are whitespace.  This has historically never been utilized (by Chisel) and is a strange language choice.
Fixes #188.
> [major] Make commas mandatory, not whitespace

- spec.md
Responding to #197, this PR adds a sentence explaining that we use a big-endian representation for values, with the index of the LSB as 0 and the MSB as one less than the length.
> Bits index convention

- revision-history.yaml
- spec.md
Intrinsic modules are kept for now, but language is added indicating they'll be deprecated in the future.
> [minor] Add generic intrinsic expressions/statements.

- spec.md
cc https://github.com/llvm/circt/pull/5075
> [nfc] Bump minimum version used to minimum CIRCT supports.

- revision-history.yaml
- spec.md
Support added for CIRCT here: https://github.com/llvm/circt/pull/7234 .
> [patch] Allow layerblocks anywhere in a module.

- revision-history.yaml
- spec.md
Add language that defines what conditionals are (they are a region where the operations in the region change their behavior based on the condition) and how different operations are affected by the condition.  This fills a hole where the behavior of commands was not explicitly specified.  Add an aside that clarifies that this means that a _trivial_ inlining will not work as a user might expect.
> [patch] Clarify existing when behavior

- spec.md
These mean same thing presently, and are used interchangeably. Standardize on the more commonly used term.
> [nfc] Replace mentions of region with block for consistency.

- spec.md
The description of the multiplication of `SInt`s was shifted a few columns too far to the left.
> [patch] Fix multiply operation description

- revision-history.yaml
- spec.md
Align extmodule port requirements re:abstract reset to match those on "public".
> [major] No abstract reset on extmodule.

- abi.md
- revision-history.yaml
Fix an ambiguity issue in the files used to enable layers.  Because layers and modules can legally contain underscore ("_") characters, this can create ambiguity because the enable files use underscores as delimiters. Avoid this entirely by changing the ABI to use a hyphen ("-") as a delimiter.
> [major] Change ABI for layer enable files

- revision-history.yaml
Move the revision history points released as 3.3.0 into a new 3.3.0 section under `oldVersions`.
> Update revision history to contain 3.3.0 release

- revision-history.yaml
- spec.md
Adjust the syntax of the `formal` declaration to no longer expect a single fixed `bound = <N>` parameter, but instead accept a list of user-defined parameters similar to an `extmodule`. The parameters can be integers, strings, arrays, and dictionaries. They are passed through to the tooling running the formal test. As we build out that tooling, we may standardize some of the parameters.
Marking this as "major" since it technically is a breaking change, but in practice there are no users of `formal` as of today and the original syntax has never been released as part of the spec.
> [major] Adjust syntax of formal unit tests

- .github/workflows/continuous-integration-ci.yml
- include/spec-template.tex
- spec.md
Bump pandoc to a newer version.  This uses version 4 as that happens to be the latest version available in macports.  Version 5 is available.
> [nfc] Bump Pandoc to version 4

- abi.md
- revision-history.yaml
- spec.md
Add the inline layer convention to the FIRRTL spec and FIRRTL ABI. Clarify some language in the spec around layers.
> [minor] Add inline layer convention

- .github/workflows/continuous-integration-ci.yml
Change from v3 to v4 as the former is no longer supported.
> [nfc] Bump upload-artifact version

- revision-history.yaml
- spec.md
Fixes https://github.com/chipsalliance/firrtl-spec/issues/276
> [patch] Replace "mod" with "rem" in primop_2expr_keyword rule

- revision-history.yaml
- spec.md
Add (the missing) `%c` is sbustitution.  This has always been generated from Chisel, it was just never put in the FIRRTL spec.
> [minor] Add %c to format string substitution

- revision-history.yaml
- spec.md
Add special substitutions.  These look like `{{Name}}`.  Add two special substitutions that we want to enable going forward:
- `{{SimulationTime}}`
- `{{HierarchicalModuleName}}`
This includes an escape sequence that can be used to get a literal `{{` in the output.  Over time, these are expected to be changed to include more special substitutions on an as-need basis.
This is a major change as it is backwards-incompatible with old FIRRTL versions.  This will break compilation of any code which used `{{` previously.
> [major] Add special substitutions

- revision-history.yaml
- spec.md
Change the target syntax to include an optional circuit.  Note: this change is strange becauase the spec was _always_ incomplete in how it discussed targets.  It never discussed the circuit, though it showed them in examples.
Change this so that the circuit name is optional.  This creates a somewhat funky syntax where targets, which never care about the circuit due to the co-location of annotation JSON in the circuit, will all be prefixed with `~|`.  This, while it would be nice to remove, provides a sigil that avoids conflicts with a legacy, undocumented target format used by Chisel originally called "named".  This would use the following:
``` ebnf
circuit , [ '.' , module , [ '.' , component ] ]
```
I originally wanted to dorp the `~|` and have all targets start with the module. …
> [minor] Add optional circuit to target syntax

- revision-history.yaml
- spec.md
This PR proposes `fprtinf` operation that output strings to a file instead of default file descriptor. https://github.com/llvm/circt/pull/8346 is PR on CIRCT
> [minor] Introduce fprintf

- abi.md
- revision-history.yaml
This PR changes the FIRRTL ABI for inline layers so that there is a single macro which, when defined, will enable the inline layer across all compilation units (circuits) in a design. This is done by removing the module-name from the macro used to enable the layer.
The type system for FIRRTL ensures that a layer-guarded hardware value is only accessed when the layer is enabled, but this is only true when a layer is enabled or disabled universally.
By including the module name in the inline layer macro, we have a distinct macro for enabling a layer for each module in a design, which would allow us to enable a layer on a module-by-module basis, which is not desirable.
Additionally, the ABI for inline macro names now uses `$` as a deliminator for name parts uniformly.
Before this PR, the …
> [major] Drop module name from inline layer macro

- README.md
Update the README.md to add much more information about what the
dependencies are, how to get them, and what the available build targets
are.
This is intended to alleviate concerns expressed in #318 about users
having difficulty running `make format` because their installation of
`pandoc` is incorrect relative to what is being tested in CI.
> [nfc] Update README.md with more dependency info

- include/firrtl.xml
- revision-history.yaml
- spec.md
Knownlayer declarations are specified on an extmodule to declare that the extmodule supports the mentioned layers. When a layer is enabled, it should also be enabled for extmodules, when the extmodule knows about the layer.
> Add knownlayer and enablelayer modifiers to extmodules
